### ISSUE TITLE
Add basic CSS file to be precompiled with the package

### ISSUE THREAD

**Issue by gabidavila** [gabidavila/react-usa-map#13]
The hover effect seen on the example: http://react-usa-map-demo.herokuapp.com/ only works because I added on the source code for the example (not the package) in the `App.css` the following: 

```css
path {
  pointer-events: all;
}
path:hover {
  opacity: 0.50;
  cursor: pointer;
}
```

Having a simple css included on the package would be nice
